/**
 * Cookie 档案的 Netscape 文本处理（纯函数，无 Electron/Node 依赖，供单测直接编译）。
 *
 * Netscape cookies.txt 行格式（TAB 分隔 7 字段）：
 *   domain \t includeSubdomains \t path \t secure \t expiry \t name \t value
 * yt-dlp `--cookies` 与 lux `-c`（文件路径）均消费此格式。
 */

export interface NetscapeCookie {
  domain: string;
  includeSubdomains: boolean;
  path: string;
  secure: boolean;
  /** 秒 epoch；0 = 会话 cookie（无过期信息） */
  expiry: number;
  /** HttpOnly 标记（从 `#HttpOnly_` 前缀解析；序列化时不再回写前缀，见下） */
  httpOnly: boolean;
  name: string;
  value: string;
}

/** yt-dlp 导出的 HttpOnly cookie 行 domain 前缀 */
const HTTPONLY_PREFIX = '#HttpOnly_';

function stripDomainPrefix(domain: string): string {
  // 解析后 domain 已剥离 #HttpOnly_，此处仅去前导点用于后缀域比较；
  // 仍容错处理残留前缀（历史损坏值）
  const idx = domain.indexOf(HTTPONLY_PREFIX);
  const d = idx >= 0 ? domain.slice(idx + HTTPONLY_PREFIX.length) : domain;
  return d.startsWith('.') ? d.slice(1) : d;
}

function hostMatchesDomain(cookieDomain: string, allowed: string): boolean {
  const bare = stripDomainPrefix(cookieDomain).toLowerCase();
  const target = allowed.toLowerCase();
  return bare === target || bare.endsWith(`.${target}`);
}

/** Chromium/WebKit epoch（自 1601-01-01 起）到 Unix epoch（1970）的秒差 */
const WEBKIT_EPOCH_OFFSET_SEC = 11_644_473_600;

/**
 * 归一化 expiry 到 Unix 秒。Netscape 格式约定为 Unix 秒，但部分 yt-dlp 构建从
 * Chrome 提取时直接写出 Chromium 原生时间戳（自 1601 起的微秒，约 1.3e16），
 * 也有工具写毫秒（约 1.7e12）。按数量级判别归一，避免 `new Date` 溢出成 Invalid Date、
 * 以及过期判定失灵。0/非法 → 0（会话 cookie）。
 */
export function normalizeExpiryToUnixSeconds(raw: number): number {
  if (!Number.isFinite(raw) || raw <= 0) return 0;
  // 自 1601 起的微秒（Chromium）：现今约 1.3e16，取 >1e15 稳妥区分
  if (raw >= 1e15) return Math.round(raw / 1e6 - WEBKIT_EPOCH_OFFSET_SEC);
  // 毫秒：现今约 1.7e12（Unix 秒最远到 ~4e9(年 2100)，与毫秒区间无重叠）
  if (raw >= 1e12) return Math.round(raw / 1000);
  return Math.round(raw);
}

/**
 * 解析 Netscape cookies.txt 文本 → cookie 结构数组。
 * 容忍空行、`#` 注释、字段不足行（跳过）。`#HttpOnly_` 前缀提取为 httpOnly 标记并从
 * domain 剥离（容错历史损坏值 `.#HttpOnly_`：只要前缀出现在第一个 TAB 前即识别）。
 */
export function parseNetscapeCookies(text: string): NetscapeCookie[] {
  const cookies: NetscapeCookie[] = [];
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.replace(/\s+$/, '');
    if (!line) continue;
    const fields = line.split('\t');
    // 数据行必有 7 字段；注释/空白（无 TAB）在此被跳过
    if (fields.length < 7) continue;
    let domainField = fields[0];
    let httpOnly = false;
    const httpOnlyIdx = domainField.indexOf(HTTPONLY_PREFIX);
    if (httpOnlyIdx >= 0) {
      httpOnly = true;
      domainField = domainField.slice(httpOnlyIdx + HTTPONLY_PREFIX.length);
    } else if (domainField.startsWith('#')) {
      // 含 7 TAB 却以 # 开头且非 HttpOnly：视为注释跳过
      continue;
    }
    const [, includeSub, path, secure, expiry, name, ...valueParts] = fields;
    if (!domainField || !name) continue;
    // 部分构建写 Chromium 原生微秒时间戳（非标准 Unix 秒），归一避免 Invalid Date
    const expiryNum = normalizeExpiryToUnixSeconds(Number(expiry));
    cookies.push({
      domain: domainField,
      includeSubdomains: includeSub.toUpperCase() === 'TRUE',
      path: path || '/',
      secure: secure.toUpperCase() === 'TRUE',
      expiry: expiryNum,
      httpOnly,
      name,
      // value 可能为空串；用 join 兜住极少数值含 TAB 的情况
      value: valueParts.join('\t'),
    });
  }
  return cookies;
}

/**
 * 序列化 cookie 结构 → Netscape cookies.txt 文本（带标准头注释）。
 * 关键：**不回写 `#HttpOnly_` 前缀**。lux 用的 cookiemonster 把任何 `#` 开头的行
 * 当注释丢弃（含 `#HttpOnly_`），会导致 SESSDATA 等 HttpOnly 登录 cookie 被吞 →「账号未登录」。
 * HttpOnly 属性经独立 `secure`/`domain` 字段无关紧要（cookie 发送与否不依赖它），
 * 故统一写普通 domain 行，yt-dlp 与 lux 均能正确读取。domain 原样保留（含前导点）。
 */
export function serializeNetscapeCookies(cookies: NetscapeCookie[]): string {
  const header = '# Netscape HTTP Cookie File\n# Generated by SmartSub\n\n';
  const lines = cookies.map((c) =>
    [
      c.domain,
      c.includeSubdomains ? 'TRUE' : 'FALSE',
      c.path || '/',
      c.secure ? 'TRUE' : 'FALSE',
      String(c.expiry || 0),
      c.name,
      c.value,
    ].join('\t'),
  );
  return header + lines.join('\n') + (lines.length ? '\n' : '');
}

/**
 * 按 cookie 域白名单过滤（后缀域匹配，剥离 `.`/`#HttpOnly_` 前缀后比较）。
 * 用于导入时丢弃无关站点 cookie，把 lux 全量发送的爆炸半径限制在单站点。
 */
export function filterCookiesByDomains(
  cookies: NetscapeCookie[],
  cookieDomains: string[],
): NetscapeCookie[] {
  return cookies.filter((c) =>
    cookieDomains.some((allowed) => hostMatchesDomain(c.domain, allowed)),
  );
}

/**
 * 原始 Cookie 串（`a=b; c=d`）→ Netscape cookie 结构。
 * 会话 cookie（expiry=0），domain 用档案主域（带前导 `.` 覆盖子域），secure=TRUE。
 */
export function cookiesFromRawString(
  raw: string,
  primaryDomain: string,
): NetscapeCookie[] {
  const domain = primaryDomain.startsWith('.')
    ? primaryDomain
    : `.${primaryDomain}`;
  const cookies: NetscapeCookie[] = [];
  for (const pair of raw.split(';')) {
    const trimmed = pair.trim();
    if (!trimmed) continue;
    const eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    const name = trimmed.slice(0, eq).trim();
    const value = trimmed.slice(eq + 1).trim();
    if (!name) continue;
    cookies.push({
      domain,
      includeSubdomains: true,
      path: '/',
      secure: true,
      expiry: 0,
      httpOnly: false,
      name,
      value,
    });
  }
  return cookies;
}

export interface CookieProfileStatus {
  cookieCount: number;
  /** 关键/最早 cookie 过期（秒 epoch）；缺省=全是会话 cookie（无过期信息） */
  expiresAt?: number;
  expired: boolean;
}

/**
 * 计算档案状态：关键 cookie（keyCookieNames）存在时取其最早过期时间，
 * 否则取所有非会话 cookie 的最早过期时间；全为会话 cookie 时 expiresAt 缺省。
 * expired：expiresAt 存在且早于 nowSeconds。
 */
export function computeCookieStatus(
  cookies: NetscapeCookie[],
  keyCookieNames: string[],
  nowSeconds: number = Math.floor(Date.now() / 1000),
): CookieProfileStatus {
  const withExpiry = cookies.filter((c) => c.expiry > 0);
  const keyed = keyCookieNames.length
    ? withExpiry.filter((c) => keyCookieNames.includes(c.name))
    : [];
  const pool = keyed.length ? keyed : withExpiry;
  let expiresAt: number | undefined;
  for (const c of pool) {
    if (expiresAt === undefined || c.expiry < expiresAt) expiresAt = c.expiry;
  }
  return {
    cookieCount: cookies.length,
    expiresAt,
    expired: expiresAt !== undefined && expiresAt < nowSeconds,
  };
}
